/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectois;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import java.util.Properties;

import javax.mail.*;

import javax.mail.internet.*;
import javax.swing.JTextArea;

/**
 *
 * @author luismiguel
 */
public class EnvioCorreo extends javax.swing.JFrame {

    /**
     * Creates new form EnvioCorreo
     */
    // Variables de la clase EjemploMetodos
	
	/** usuarioEmisor obtiene y contiene 
	 *  el correo electronico de usuario emisor.
	 */
	String usuarioEmisor;
	
	/** claveEmisor obtiene y contiene 
	 *  la clave del correo electronico del usuario emisor.
	 */
	String claveEmisor;
	
	/** usuarioReceptor obtiene y contiene 
	 *  el correo electronico de usuario receptor.
	 */
	String usuarioReceptor;
	
	/** asuntoMensaje  obtiene y contiene 
	 *  el asunto del mensaje a enviar.
	 */
	String asuntoMensaje;
	
	/** contenidoMensaje obtiene y contiene 
	 *  el cuerpo en texto plano del mensaje.
	 */
	String contenidoMensaje;
    public EnvioCorreo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Et = new javax.swing.JLabel();
        EtAsunto = new javax.swing.JLabel();
        EtMensaje = new javax.swing.JLabel();
        CampoCorreoDestino = new javax.swing.JTextField();
        CampoAsunto = new javax.swing.JTextField();
        CampoMensaje = new javax.swing.JScrollPane();
        CampoMensaje2 = new javax.swing.JTextArea();
        BotonEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Et.setText("Email Destino");

        EtAsunto.setText("Asunto");

        EtMensaje.setText("Mensaje");

        CampoMensaje2.setColumns(20);
        CampoMensaje2.setRows(5);
        CampoMensaje.setViewportView(CampoMensaje2);

        BotonEnviar.setText("Enviar");
        BotonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Et)
                            .addComponent(EtAsunto))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoCorreoDestino)
                            .addComponent(CampoAsunto, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(EtMensaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(CampoMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonEnviar)
                .addGap(147, 147, 147))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Et)
                    .addComponent(CampoCorreoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtAsunto)
                    .addComponent(CampoAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EtMensaje)
                    .addComponent(CampoMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(BotonEnviar)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Session sesionok;
    private void BotonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEnviarActionPerformed
                
              crearMensaje(sesionok,usuarioEmisor);
              /*  System.out.println("accion event enviar");
               System.out.println(usuarioEmisor);
               System.out.println(claveEmisor);
       
                */
    }//GEN-LAST:event_BotonEnviarActionPerformed
    
	/**
	 * Método ValidarSesion se encarga de validar y autenticar mediante 
	 * el protocolo smtp el correo y la clave del usuario emisor para
	 * conectarse con Gmail.
	 * Este método llama al método crearMensaje. 
	 *  
	 * @param emisor contiene el correo del usuario emisor.
	 * @param clave  contiene la clave del usuario emisor.
	 */
    
         public void obtenerDatos(String correo, Session sesion){
		
		sesionok=sesion;
		usuarioEmisor=correo;
                /*
                System.out.println("metodo obtener en envio correo");
                 System.out.println(usuarioEmisor);
                 System.out.println(sesionok);*/
		
	}
	/**
	 * Método crearMensaje recibe por parametro la sesion valida
	 * y el correo del usuario emisor para proceder a crear el 
	 * mensaje.
	 * Este método llama al método enviarMensaje. 
	 *
	 * @param session   es un objeto de la clase Session y me dice la sesion valida
	 * @param emisorFrom en una variable que contiene el correo del usuario emisor
	 */
       
       
        
        
        
     
	public void crearMensaje(Session session, String emisorFrom){
		    
		Message message = new MimeMessage(session);
		
		try {
			message.setFrom( new InternetAddress(emisorFrom));
			usuarioReceptor=CampoCorreoDestino.getText();
                        message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(usuarioReceptor)
					);
			
			asuntoMensaje=CampoAsunto.getText();
			message.setSubject(asuntoMensaje);
			contenidoMensaje=CampoMensaje2.getText();
                       	message.setText(contenidoMensaje);
			
			System.out.print("EL MENSAJE HA SIDO CREADO" + "\n");
			enviarMensaje(message);
			
		} catch (MessagingException e) {
			
			System.out.print("EL MENSAJE NO HA SIDO CREADO");
		}
		
		
	}// Cierre del Método
	
	
	/**
	 * Método enviarMensaje solo se encarga de recibir por 
	 * parametro un objeto de la clase Message  y de enviar
	 * el mensaje al destinatario.
	 * 
	 * @param mensaje es el objeto de la clase Message que 
	 * contiene el asunto y contenido del mensaje.
	 */
	public void enviarMensaje(Message mensaje){
		
		try {
			Transport.send(mensaje);
			System.out.print("EL MENSAJE HA SIDO ENVIADO EXITOSAMENTE");
		} catch (MessagingException e) {
			System.out.print("EL MENSAJE NO SE HA PODIDO ENVIAR");
		}
	}// Cierre del Método
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnvioCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnvioCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnvioCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnvioCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnvioCorreo().setVisible(true);
            }
        });
    }

    public JTextField getCampoAsunto() {
        return CampoAsunto;
    }

    public void setCampoAsunto(JTextField CampoAsunto) {
        this.CampoAsunto = CampoAsunto;
    }

    public JTextField getCampoCorreoDestino() {
        return CampoCorreoDestino;
    }

    public void setCampoCorreoDestino(JTextField CampoCorreoDestino) {
        this.CampoCorreoDestino = CampoCorreoDestino;
    }

    public JScrollPane getCampoMensaje() {
        return CampoMensaje;
    }

    public void setCampoMensaje(JScrollPane CampoMensaje) {
        this.CampoMensaje = CampoMensaje;
    }

    public JTextArea getCampoMensaje2() {
        return CampoMensaje2;
    }

    public void setCampoMensaje2(JTextArea CampoMensaje2) {
        this.CampoMensaje2 = CampoMensaje2;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonEnviar;
    private javax.swing.JTextField CampoAsunto;
    private javax.swing.JTextField CampoCorreoDestino;
    private javax.swing.JScrollPane CampoMensaje;
    private javax.swing.JTextArea CampoMensaje2;
    private javax.swing.JLabel Et;
    private javax.swing.JLabel EtAsunto;
    private javax.swing.JLabel EtMensaje;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
