/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoingsoft;

import java.awt.Image;
import java.util.Locale;
import java.util.Properties;
import java.util.ResourceBundle;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author luismiguel
 */
public class login extends javax.swing.JFrame {
     // Variables de la clase login
	
	/** usuarioEmisor obtiene y contiene 
	 *  el correo electronico de usuario emisor.
	 */
	String usuarioEmisor;
	
	/** claveEmisor obtiene y contiene 
	 *  la clave del correo electronico del usuario emisor.
	 */
	String claveEmisor;
	 String idioma;
	
	ResourceBundle fuente;
	
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame4 = new javax.swing.JFrame();
        Login = new javax.swing.JPanel();
        EtCorreo = new javax.swing.JLabel();
        EtContrasena = new javax.swing.JLabel();
        CampoContrasena = new javax.swing.JPasswordField();
        CampoCorreo = new javax.swing.JTextField();
        BotonIniciar = new javax.swing.JButton();
        opcionIdioma = new javax.swing.JComboBox<>();
        EtIdioma = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesión");
        setResizable(false);

        EtCorreo.setText("Correo");

        EtContrasena.setText("Contraseña");

        BotonIniciar.setText("Iniciar Sesion");
        BotonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarActionPerformed(evt);
            }
        });

        opcionIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles", "Frances", " " }));
        opcionIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionIdiomaActionPerformed(evt);
            }
        });

        EtIdioma.setText("Idioma");

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addComponent(BotonIniciar)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EtCorreo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EtContrasena, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(32, 32, 32)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(CampoCorreo))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addComponent(EtIdioma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(opcionIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtCorreo)
                    .addComponent(CampoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtContrasena)
                    .addComponent(CampoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(BotonIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtIdioma))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * Método obtenerDatos se encarga de obtener el correo y la clave
	 * del usuario emisor.
	 * y luego lo envia por parametro al método validarSesion.
	 * Este método llama al método validarSesion. 
	 * 
	 */
	public void obtenerDatos(){
		
		
		usuarioEmisor=CampoCorreo.getText();
		
		claveEmisor=CampoContrasena.getText();
                 System.out.println(usuarioEmisor);
                 System.out.println(claveEmisor);
                validarSesion(usuarioEmisor,claveEmisor);
                
		
	}// Cierre del Método

        
  

        /**
	 * Método ValidarSesion se encarga de validar y autenticar mediante 
	 * el protocolo smtp el correo y la clave del usuario emisor para
	 * conectarse con Gmail.
	 * Este método llama al método crearMensaje. 
	 *  
	 * @param emisor contiene el correo del usuario emisor.
	 * @param clave  contiene la clave del usuario emisor.
	 */
	
        Session sesion;
	public void validarSesion (String emisor, String clave){
                 
            Properties props = new Properties();
		
		props.put("mail.smtp.auth", "true");
		props.put("mail.smtp.starttls.enable", "true");
		props.put("mail.smtp.host", "smtp.gmail.com");
		props.put("mail.smtp.port", "587");
		
		 sesion= Session.getInstance(props, new javax.mail.Authenticator(){
			protected PasswordAuthentication
		getPasswordAuthentication(){
				return new PasswordAuthentication(emisor,clave);
			}
		});
		        
		
		
	}// Cierre del Método
	
    private void BotonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarActionPerformed
        
                        
               obtenerDatos();
               
                 LecturaCorreo ejecutaraccion =new LecturaCorreo();
                ejecutaraccion.obtenerDatos(usuarioEmisor, claveEmisor,idioma);
               
                ejecutaraccion.traducir(fuente);
                System.out.println(usuarioEmisor);
                ejecutaraccion.VentanaPrincipal();
                   System.out.println(sesion);
               
                
              this.setVisible(false);
	               
    }//GEN-LAST:event_BotonIniciarActionPerformed

    public JComboBox<String> getOpcionIdioma() {
        return opcionIdioma;
    }

    public void setOpcionIdioma(JComboBox<String> opcionIdioma) {
        this.opcionIdioma = opcionIdioma;
    }

    private void opcionIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionIdiomaActionPerformed
      if (evt.getSource()==opcionIdioma) {
          idioma=(String)opcionIdioma.getSelectedItem();
           detectorIdioma(idioma);
           
          
      }
    }//GEN-LAST:event_opcionIdiomaActionPerformed
     public void ImageAndLabels( ) {
          JFrame frame = new JFrame("image and labels");
          
            setLayout(new BoxLayout(this, BoxLayout.PAGE_AXIS));
            add( new JLabel( new ImageIcon("./ico.png ")));
           
        }
      protected void detectorIdioma(String idioma) {
           Locale region = null;
          switch(idioma){
    case "Español":
        region=new Locale("es","ES");
        
        break;          
    case "Ingles":
        region=new Locale("en","US");
        
        break;
    case "Frances":
        region=new Locale("fr","FR");
        break;
        }
        
          fuente= ResourceBundle.getBundle("proyectoingsoft/Bundle",region);
         
          
          traducir(fuente);
          
         }
      
      public void traducir(ResourceBundle fuente){
      BotonIniciar.setText(fuente.getString("login.BotonIniciar.text"));
      EtCorreo.setText(fuente.getString("login.EtCorreo.text"));
      EtContrasena.setText(fuente.getString("login.EtContrasena.text"));
      this.setTitle(fuente.getString("login.title"));
      EtIdioma.setText(fuente.getString("login.EtIdioma.text"));
      
      
      
           
      }
      
      
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new login().VentanaPrincipal();
            }
        });
    }
        public void VentanaPrincipal(){
       
        ImageIcon ImageIcon = new ImageIcon(getClass().getResource("images/ico.png"));
        Image Image = ImageIcon.getImage();
        this.setIconImage(Image);
        
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
    }
   

    public JPasswordField getCampoContrasena() {
        return CampoContrasena;
    }

    public void setCampoContrasena(JPasswordField CampoContrasena) {
        this.CampoContrasena = CampoContrasena;
    }

    public JTextField getCampoCorreo() {
        return CampoCorreo;
    }

    public void setCampoCorreo(JTextField CampoCorreo) {
        this.CampoCorreo = CampoCorreo;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIniciar;
    private javax.swing.JPasswordField CampoContrasena;
    private javax.swing.JTextField CampoCorreo;
    private javax.swing.JLabel EtContrasena;
    private javax.swing.JLabel EtCorreo;
    private javax.swing.JLabel EtIdioma;
    private javax.swing.JPanel Login;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JComboBox<String> opcionIdioma;
    // End of variables declaration//GEN-END:variables
}
