/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoingsoft;

import java.awt.Dimension;
import java.awt.Image;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author luismiguel
 */
public class VisualGrafica extends javax.swing.JFrame {
Graficos  migrafico = new Graficos ();
    /**
     * Creates new form Graficas
     */
    public VisualGrafica() {
        initComponents();
    }
        int contadorintegrante1=0;
        ResourceBundle fuente;
        int contadorintegrante2=0;
         int contadorintegrante3=0;
         
	/** usuarioEmisor obtiene y contiene 
	 *  el correo electronico de usuario emisor.
	 */
	String usuarioEmisor;
	
	/** claveEmisor obtiene y contiene 
	 *  la clave del correo electronico del usuario emisor.
	 */
	String claveEmisor;
	
	/** usuarioReceptor obtiene y contiene 
	 *  el correo electronico de usuario receptor.
	 */
        
        String idioma;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaGrafica = new javax.swing.JPanel();
        BotonGraficar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonRefrescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout areaGraficaLayout = new javax.swing.GroupLayout(areaGrafica);
        areaGrafica.setLayout(areaGraficaLayout);
        areaGraficaLayout.setHorizontalGroup(
            areaGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        areaGraficaLayout.setVerticalGroup(
            areaGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        BotonGraficar.setText("Graficar");
        BotonGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGraficarActionPerformed(evt);
            }
        });

        BotonSalir.setText("Cerrar Sesion");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        BotonRefrescar.setText("Refrescar");
        BotonRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRefrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(areaGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(BotonSalir)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(BotonGraficar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonRefrescar)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonGraficar)
                    .addComponent(BotonRefrescar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void obtenerDatos(int contintegrante1,int contintegrante2, int contintegrante3){
		
                contadorintegrante1=contintegrante1;
                contadorintegrante2=contintegrante2;
                contadorintegrante3=contintegrante3;
               
              
		
	}
 
  public void traducir(ResourceBundle fuenteok){
      fuente=fuenteok;
  BotonGraficar.setText(fuente.getString("VisualGrafica.BotonGraficar.text"));
  this.setTitle(fuente.getString("VisualGrafica.title"));
  BotonSalir.setText(fuente.getString("VisualGrafica.BotonSalir.text"));
  
  }
    private void BotonGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGraficarActionPerformed

              //tamaño del grafico
        Dimension d = areaGrafica.getSize();//toma el tamaño del contenedor
        //se crean los datos
        int[] valores = {contadorintegrante1,contadorintegrante2,contadorintegrante3};
        String[] arg1 = {"Integrante 1","Integrante 2","Luis Miguel"};
        String[] arg2 = {"Mensajes","Mensajes","Mensajes"};
        //titulo, lateral 1, lateral 2
        String[] data = {"Interacciones","INBOX","Mensajes"};
        //se crea el grafico
        migrafico.crear_grafico_de_barras(d, valores, arg2, arg1, data);
        //se crea un jlabel para colocar el grafico
        JLabel j = new JLabel();
        j.setBounds(0, 0, d.width, d.height);
        //se carga el grafico de memoria
        migrafico.cargar_grafico(j);
        //se añade al contenedor
        areaGrafica.add(j);
        this.repaint();

        // TODO add your handling code here:
    }//GEN-LAST:event_BotonGraficarActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed
public void obtenerDatos(String emisor, String contrasena,String idiomaregion){
		usuarioEmisor=emisor;
                claveEmisor=contrasena;
             idioma=idiomaregion;
	}
    private void BotonRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRefrescarActionPerformed
      
       
       LecturaCorreo ejecutaraccion =new LecturaCorreo();
                ejecutaraccion.obtenerDatos(usuarioEmisor, claveEmisor,idioma);
               ejecutaraccion.VentanaPrincipal();
               ejecutaraccion.traducir(fuente);
                
                
                this.setVisible(false);
    }//GEN-LAST:event_BotonRefrescarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void VentanaPrincipal(){
       
        ImageIcon ImageIcon = new ImageIcon(getClass().getResource("images/ico.png"));
        Image Image = ImageIcon.getImage();
        this.setIconImage(Image);
        
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGraficar;
    private javax.swing.JButton BotonRefrescar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JPanel areaGrafica;
    // End of variables declaration//GEN-END:variables
}
